openapi: 3.0.1
info:
  title: Backend Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9595"
paths:
  /search:
    get:
      operationId: getSearch
      parameters:
      - name: params
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items: {}
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
  /read/{id}:
    get:
      operationId: getReadId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
  /{id}/_history/{vid}:
    get:
      operationId: getIdHistoryVid
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: vid
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
  /{id}:
    put:
      operationId: putId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
    delete:
      operationId: deleteId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
    patch:
      operationId: patchId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
  /create:
    post:
      operationId: postCreate
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
components: {}
