[package]
org = "isurus"
name = "eob_source_connect"
version = "0.1.0"
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "wso2healthcare"
name = "healthcare.fhir.r4"
version = "0.1.15"

[[dependency]]
org = "wso2healthcare"
name = "healthcare.fhir.r4.parser"
version = "0.1.15"